apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: retail-store
  source:
    repoURL: https://github.com/rawatmeghaa/retail-store-sample-app.git
    targetRevision: main
    path: src/ui/chart
    helm:
      valueFiles:
        - values.yaml
      values: |
        ingresses:
          - name: domain
            className: "nginx"
            hosts:
              - retail-store.rwtmeghna.com
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            tls:
              - secretName: tls-secret
                hosts:
                  - retail-store.rwtmeghna.com
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
